### ISSUE TITLE
maintainers and contacts for the pipy package

### ISSUE THREAD

**Issue by tomsail** [seareport/xarray-selafin#12]
A pipy package is available 

https://pypi.org/project/xarray-selafin-backend/

@lucduron may I add you to the authors and contact persons? I think you're the most competent person to be listed there :) 

@sebourban, I don't think it is relevant to put someone from EDF at this point but let me know if you think otherwise.

**Comment by lucduron** [comment]
Ok to include my contact, I created a [PyPI account](https://pypi.org/user/lucduron/).

**Comment by lucduron** [comment]
Having another `selafin-io` repository on PyPI would be perfect ;)
It should then be a dependency of PyTelTools and xarray-selafin.

**Comment by tomsail** [comment]
> Having another `selafin-io` repository on PyPI would be perfect ;)
> It should then be a dependency of PyTelTools and xarray-selafin.

Can you develop? I am not sure I understood completely

**Comment by sebourban** [comment]
> A pipy package is available
> 
> https://pypi.org/project/xarray-selafin-backend/
> 
> @lucduron may I add you to the authors and contact persons? I think you're the most competent person to be listed there :)
> 
> @sebourban, I don't think it is relevant to put someone from EDF at this point but let me know if you think otherwise.

The link does not seem to work for me. You can add me as contact. I am all for having a separate branch with separated scripts.

**Comment by sebourban** [comment]
> sorry @sebourban: please also create an account on [pypi.org](pypi.org) so that I can add you to the contributors/contacts list

OK - c'est fait - merci Thomas (@sebourban)
