### ISSUE TITLE
Limit compulsory objects in DataSet dims/data_vars/attrs/coords and distinguish 2D/3D

### ISSUE THREAD

**Issue by lucduron** [seareport/xarray-selafin#13]
What do you think of removing the **dimension "plan"** for 2D (it would only be available in 3D)?

I would also remove some **redondant data**:

- meshx vs x coords
- meshy vs y coords
- ipobo2 attribute vs ipobo3 attribute
- ...

The aim is to be able to write a Selafin file from a more simple DataSet directly.
Compulsory data would be : x, y, ikle2 and data_vars. All other data would be optional.

**Comment by tomsail** [comment]
I like the idea

**Comment by lucduron** [comment]
I will try to commit something to have a simpler DataSet.
