### ISSUE TITLE
Make dask an optional dependency

### ISSUE THREAD

**Issue by pmav99** [seareport/xarray-selafin#2]
Minor issue, but I am opening the ticket so that I don't forget about it.

Currently, `dask` is a mandatory dependency of the xelafin backend. Nevertheless `dask` is an optional dependency of xarray. 

My understanding is that it should be possible to develop the backend so that it can work either "eagerly" (without dask) or "lazily" (with dask). For now I guess that we should focus on getting either mode to work, but in the future we should test/support both.

For the record, it might be easier to fix the issues we have with `write` in the eager mode.

**Comment by tomsail** [comment]
> For the record, it might be easier to fix the issues we have with write in the eager mode.

exactly. I will implement first the "eager" mode and see it fixes the issue with slice indices.
