### ISSUE TITLE
ikle indexing: pyTelTools ikle = slf ikle + 1

### ISSUE THREAD

**Issue by tomsail** [seareport/xarray-selafin#22]
pyTelTools ikle indexing (or triangle connectivity) has a 1 increment (they start from 1) compared to the traditional Selafin indexing (that start from 0). 
Maybe I would add a warning (and even better an example with a triplot/tricontour plot using matplotlib) so that users understand the subtility.

**Comment by lucduron** [comment]
Selafin and PyTelTools indexing are identical, it is based on Fortran numbering (starts from 1).
But Python librairies (triplot for example) would require 0-indexed.

**Comment by tomsail** [comment]
TELEMAC's Selafin class [0-indexes IKLE](https://gitlab.pam-retd.fr/otm/telemac-mascaret/-/blob/main/scripts/python3/data_manip/formats/selafin.py?ref_type=heads#L168) upon reading.
and [1-indexes back](https://gitlab.pam-retd.fr/otm/telemac-mascaret/-/blob/main/scripts/python3/data_manip/formats/selafin.py?ref_type=heads#L325) the IKLE upon writing

**Comment by tomsail** [comment]
So indeed they are 1 indexes in Fortran and pyTelTools, but the Selafin class 0-indexes in the python environment
